window.devSsoIdp = {
    responseError: 'access_denied',
};
window.devSsoIdp.CLIENT_IDS = 'CLIENT_IDS_GO_HERE';
window.devSsoIdp.PERCENT_ENCODED_REDIRECT_URIS =
    'PERCENT_ENCODED_REDIRECT_URIS_GOES_HERE';
window.devSsoIdp.IGNORE_RESPONSE_TYPE_VALIDATION =
    'IGNORE_RESPONSE_TYPE_VALIDATION_GOES_HERE';
window.devSsoIdp.IGNORE_CLIENT_ID_VALIDATION =
    'IGNORE_CLIENT_ID_VALIDATION_GOES_HERE';
window.devSsoIdp.IGNORE_SCOPE_VALIDATION = 'IGNORE_SCOPE_VALIDATION_GOES_HERE';
window.devSsoIdp.IGNORE_REDIRECT_URI_VALIDATION =
    'IGNORE_REDIRECT_URI_VALIDATION_GOES_HERE';
window.devSsoIdp.envVarServerValidationResult =
    'ENV_VAR_SERVER_VALIDATION_RESULT_GOES_HERE';
